define([
    'modules/room/directives/ngPager',
    'modules/room/factories/enumerate',
    'modules/room/factories/stateAdapter',
    'modules/room/services/messageService',
    'modules/room/controllers/test',
    'modules/room/controllers/bar',
    'modules/room/controllers/build',
    'modules/room/controllers/buildForm',
    'modules/room/controllers/roles',
    'modules/room/controllers/rooms',
    'modules/room/controllers/message',
    'modules/room/controllers/users',
    'modules/room/controllers/home',
    'modules/room/controllers/state',
    'modules/room/controllers/roomType',
    'modules/room/controllers/roomTypeForm',
    'modules/room/controllers/eventSystem',
    'modules/room/controllers/eventRoom',
    'modules/room/controllers/identitySettings',
    'modules/room/controllers/parameterSettings',
    'modules/room/controllers/roomForm',
    'modules/room/controllers/mode',
    'modules/room/controllers/roomRange',
    'modules/room/filters/imagePath',
    'modules/room/filters/roomStatus'
], function () {
    'use strict';
});