require.config({
    removeCombined: true,
    fileExclusionRegExp: /^\./,
    paths: {
        'api-check': '../bower_components/api-check/dist/api-check.min',
        'ng-table': '../bower_components/ng-table/dist/ng-table.min',
        'jquery-slimscroll': '../bower_components/jquery-slimscroll/jquery.slimscroll.min',
        'pace': '../bower_components/pace/pace.min',
        'metisMenu': 'js/metisMenu.min',
        'cropper': '../bower_components/cropper/dist/cropper.min',
        'angularjs-slider': '../bower_components/angularjs-slider/dist/rzslider.min',
        'angular': '../bower_components/angular/angular.min',
        'jquery': '../bower_components/jquery/dist/jquery.min',
        'jquery-ui': '../bower_components/jquery-ui/jquery-ui.min',
        'bootstrap': '../bower_components/bootstrap/dist/js/bootstrap.min',
        'ui-bootstrap-tpls': '../bower_components/angular-bootstrap/ui-bootstrap-tpls.min',
        'angular-ui-router': '../bower_components/angular-ui-router/release/angular-ui-router.min',
        'ui-switch': 'js/angular-ui-switch.min',
        'contabs': 'js/contabs.min',
        'hplus': 'js/hplus.min',
        'layer': 'js/layer.min',
        'mobiscroll': 'js/mobiscroll.custom-2.5.2.min',
        'app/application': 'js/app.application.min'
    },
    shim: {},
    exclude: [
        'api-check',
        'ng-table',
        'jquery-slimscroll',
        'pace',
        'metisMenu',
        'cropper',
        'angularjs-slider',
        'angular',
        'jquery',
        'jquery-ui',
        'bootstrap',
        'ui-bootstrap-tpls',
        'angular-ui-router',
        'ui-switch',
        'hplus',
        'contabs',
        'layer',
        'mobiscroll',
        'app/application'
    ]
});